### ISSUE TITLE
Switch to ruby 2.0preview

### ISSUE THREAD

**Issue by drapergeek** [drapergeek/wuzup#15]
Heroku supports ruby 2.0.  I think this project is basic enough right now to just jump on the bandwagon and go ahead and set it up and find any holes.

**Comment by brentm5** [comment]
Only thing i would be concerned about is gem support and Travis CI support... believe they should be good but i cant find explicitly about travis.

**Comment by drapergeek** [comment]
Quite true on travis but I know heroku is supported.
